version: '3.7'
services:
  nexus:
    image: sonatype/nexus3:3.66.0
    ports:
      - 8081:8081
    volumes:
      - ./nexus-data:/nexus-data
    extra_hosts:
      - "mbasit3.ftcwifi.com:192.169.3.1"
    restart: always
